region              = "ap-south-1"
vpc_cidr            = "10.0.0.0/16"
public_subnet_cidr  = "10.0.1.0/24"
private_subnet_cidr = "10.0.2.0/24"
availability_zone_a = "ap-south-1a"
availability_zone_b = "ap-south-1b"
name                = "myapp"
environment         = "dev"